GLOSSARY = {
    "ETF": "Exchange-Traded Fund — a basket of stocks or bonds packaged into a single investment that trades on a stock exchange like a regular stock. ETFs are low-cost, broadly diversified, and easy to buy through any brokerage.",
    "Allocation": "The percentage of your portfolio invested in each asset. For example, 60% stocks, 40% bonds. Your allocation is the primary driver of your expected return and risk level.",
    "Diversification": "Spreading money across many different investments so no single loss can sink the whole portfolio. Buying a single ETF can instantly diversify you across thousands of companies.",
    "Index Fund": "A fund that tracks a market index (like the S&P 500) rather than trying to beat it. Passively managed — fees are much lower, and index funds historically outperform most actively managed funds over the long run.",
    "Rebalancing": "Periodically buying or selling assets to restore your target allocation. Over time, winners grow to dominate your portfolio — rebalancing trims them back and reinvests in the laggards.",
    "Risk Tolerance": "How much short-term loss you can stomach — emotionally and financially — in exchange for higher potential long-term gains. Higher tolerance → more stocks. Lower tolerance → more bonds.",
    "Bond": "A loan you make to a government or company. They pay you interest over time and return your principal at maturity. Bonds are more stable than stocks but grow more slowly.",
    "Equity": "Ownership in a company. Stocks (equities) have higher growth potential than bonds but more volatility. Over long periods, equities have historically been the best-performing major asset class.",
    "Expense Ratio": "The annual fee an ETF charges, expressed as a percentage of your investment. A 0.03% ratio on $10,000 costs just $3/year. Low fees are one of the most reliable ways to improve long-term returns.",
    "Compound Growth": "Earning returns on your returns. A dollar invested today grows not just on itself, but on every dollar of gain it generates. Over decades, this creates exponential growth — the most powerful force in long-term investing.",
    "Dollar-Cost Averaging": "Investing a fixed amount on a regular schedule (like $200/month) regardless of market conditions. You automatically buy more shares when prices are low, smoothing out the impact of volatility over time.",
    "Roth IRA": "A retirement account where you contribute after-tax dollars. Your investments grow tax-free and withdrawals in retirement are also tax-free. Best for people who expect to be in a higher tax bracket in retirement.",
    "Traditional IRA": "A retirement account where contributions may be tax-deductible. You pay taxes when you withdraw in retirement. Best for people who expect to be in a lower tax bracket in retirement.",
    "401(k)": "An employer-sponsored retirement account. Contributions are pre-tax, lowering your taxable income today. Many employers match contributions — always invest enough to capture the full match.",
    "Volatility": "How much an investment's price swings over time. Stocks are highly volatile. Bonds are calmer. A diversified mix smooths the ride without sacrificing long-term returns.",
    "VTI": "Vanguard Total Stock Market ETF — owns a small piece of nearly every publicly traded U.S. company. Expense ratio: 0.03%. The closest thing to owning the entire U.S. economy in one fund.",
    "VXUS": "Vanguard Total International Stock ETF — same concept as VTI but for companies outside the U.S. Covers Europe, Asia, and emerging markets. Adds geographic diversification.",
    "BND": "Vanguard Total Bond Market ETF — holds thousands of U.S. government and corporate bonds. Lower growth than stocks but steadier, and often rises when stocks fall.",
    "BNDX": "Vanguard Total International Bond ETF — international bonds, adding geographic diversification to the stable, lower-risk portion of your portfolio.",
}
